### PR TITLE
use main branch image for running circle tests

### PR DESCRIPTION
**Pull request by starswan**
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1353)

## What changed and why

Need to use main branch for circle tests, otherwise all builds fail

## Checklist

Before you ask people to review this PR:

- Tests and rubocop should be passing
- Branch is generally up to date with main Github - definitely no conflicts
- No unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- PR description says *what* changed and *why*, with a link to the JIRA story.
- Diff has been checked for unexpected changes being included.
- Commit messages say why the change was made.

### CODE REVIEW

**Review by MazOneTwoOne — APPROVED** [review]
Approved.

So does that mean, before the change (as in now), we'll never have a image for the `run_specs` job to use, as it never existed?

**Comment by MazOneTwoOne** [comment]
Another question: How do we build this image `checkclientqualifiesdocker/circleci-image:main`? Is is after a branch is merged to main? 

We build the branches docker test image `checkclientqualifiesdocker/circleci-image:${{ github.ref_name }}`, based on the GitHub name, but never use it on the branch, as it will be pointed to `checkclientqualifiesdocker/circleci-image:main`? 

I might not be understanding.

**Comment by starswan** [comment]
> Another question: How do we build this image `checkclientqualifiesdocker/circleci-image:main`? Is is after a branch is merged to main?
> 
> We build the branches docker test image `checkclientqualifiesdocker/circleci-image:${{ github.ref_name }}`, based on the GitHub name, but never use it on the branch, as it will be pointed to `checkclientqualifiesdocker/circleci-image:main`?
> 
> I might not be understanding.

The image gets built on a push to main - so we only have a main image. It got broken when I merged EL-1353 this morning

**Comment by MazOneTwoOne** [comment]
> > Another question: How do we build this image `checkclientqualifiesdocker/circleci-image:main`? Is is after a branch is merged to main?
> > We build the branches docker test image `checkclientqualifiesdocker/circleci-image:${{ github.ref_name }}`, based on the GitHub name, but never use it on the branch, as it will be pointed to `checkclientqualifiesdocker/circleci-image:main`?
> > I might not be understanding.
> 
> The image gets built on a push to main - so we only have a main image. It got broken when I merged EL-1353 this morning

That makes sense. I see that `.github/workflows/browser_tools_docker_image.yml` has been changed to have this:

```
  push:
    branches:
      - main
```

**Pull request merged**
